### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [23]:
# перше завдання

import numpy as np

vector_1 = np.random.rand(10)
vector = np.round(vector_1,2)
vector

array([0.39, 0.84, 0.25, 0.79, 0.54, 0.82, 0.51, 0.23, 0.83, 0.3 ])

In [24]:
# друге завдання
matrix = np.array([[11, 14, 17],
                   [20, 23, 26],
                   [29, 32, 35]])
matrix

array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

In [25]:
vector.shape, matrix.shape

((10,), (3, 3))


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [26]:
#2.1

vector_aug = vector + 10

matrix_aug = matrix + 10
matrix_aug, vector_aug

(array([[21, 24, 27],
        [30, 33, 36],
        [39, 42, 45]]),
 array([10.39, 10.84, 10.25, 10.79, 10.54, 10.82, 10.51, 10.23, 10.83,
        10.3 ]))

In [27]:
#2.2


vector_mult = vector * 2

matrix_mult = matrix * 2
matrix_mult, vector_mult

(array([[22, 28, 34],
        [40, 46, 52],
        [58, 64, 70]]),
 array([0.78, 1.68, 0.5 , 1.58, 1.08, 1.64, 1.02, 0.46, 1.66, 0.6 ]))

In [28]:
#2.3

squared_vector = vector ** 2
squared_matrix = matrix ** 2
squared_matrix, squared_vector

(array([[ 121,  196,  289],
        [ 400,  529,  676],
        [ 841, 1024, 1225]]),
 array([0.1521, 0.7056, 0.0625, 0.6241, 0.2916, 0.6724, 0.2601, 0.0529,
        0.6889, 0.09  ]))


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [29]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [38]:
#3.1

result_matrix = B @ A
result_matrix, result_matrix.shape

(array([[0.7281, 0.5202],
        [0.2034, 0.2846]]),
 (2, 2))

In [44]:
#3.2

result_matrix_C = result_matrix @ C
result_matrix_C, result_matrix_C.shape

# Я думала, що результат буде 2х2, але вийшло 2х1

(array([[0.5202],
        [0.2846]]),
 (2, 1))

In [46]:
#3.3

result_matrix_D = result_matrix @ D
result_matrix_D, result_matrix_D.shape
# матриці С та Д мають однакову к-ть рядків та стовпців. При множені result_matrix @ D я отримала результат 2х2.
#Тому можу припустити, що при множені на С яотримала результат 2х1 через те. що в першій колонці значення було нульове

(array([[0.5202, 0.7281],
        [0.2846, 0.2034]]),
 (2, 2))


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [49]:
#4.1

result_matrix_transpos = result_matrix.T
result_matrix_transpos

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [56]:
#4.2

vector_transpos = vector.T
vector_transpos, vector_transpos.shape

#змін після транспонування не бачу, по шейпу також без змін

(array([0.39, 0.84, 0.25, 0.79, 0.54, 0.82, 0.51, 0.23, 0.83, 0.3 ]), (10,))

In [54]:
vector, vector.shape

(array([0.39, 0.84, 0.25, 0.79, 0.54, 0.82, 0.51, 0.23, 0.83, 0.3 ]), (10,))

In [62]:
#4.3

column_vector = np.expand_dims(vector_transpos, axis = 1)
column_vector, column_vector.shape
# тепер можна бачити зміну матриця має розмірність 10х1, в той час, як просто vector має розмірність 10. Тобто ми додали колонку

(array([[0.39],
        [0.84],
        [0.25],
        [0.79],
        [0.54],
        [0.82],
        [0.51],
        [0.23],
        [0.83],
        [0.3 ]]),
 (10, 1))

In [65]:
#4.4

column_vector_transpos = column_vector.T
column_vector_transpos, column_vector_transpos.shape

# після транспонування vector має розмірність 1х10

(array([[0.39, 0.84, 0.25, 0.79, 0.54, 0.82, 0.51, 0.23, 0.83, 0.3 ]]),
 (1, 10))